### PR TITLE
Preliminary subdirectory support. refs #50

### PR DESCRIPTION
**Pull request by gazpachoking**
I had an initial go at allowing subdirectory support. Could it be this easy? Is there other stuff that needs to be updated?

TODO?:

- [ ] I'm thinking paths should probably be split on directory separators, and each section passed to make canonical separately.

### CODE REVIEW

**Comment by gazpachoking** [comment]
Been testing this out a bit in preparation for rolling our old trac wiki over to this, and it seems to be handling everything as expected.

**Comment by scragg0x** [comment]
Thanks, I will do some tests as well before I push to pypi.

**Comment by gazpachoking** [comment]
@scragg0x Been thinking a bit more... One thing I wasn't sure of, should the 128 length limit be per component of path, and not for the whole thing? I also think we need to split path before certain sanitizing, e.g. things like removing the leading underscore won't currently work for dirs.

**Comment by scragg0x** [comment]
@gazpachoking You are correct. Each folder/file should be no longer than 63 chars.  As for total path size no longer than 436.  I only care about the very beginning underscore, so subsequent ones are ok.  And lets make sure the path doesn't end in a /

63 = floor( 256 (file name byte limit) / 4 (unicode max bytes per char) )

436 = (2000[(link)](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers) - 256 (domain max size)) / 4 (unicode max bytes)

Not quite sure about unicode in the URL but I think dividing by 4 is on the safe size.
If you want to do this go for it.  I won't have time until tomorrow evening.

**Pull request merged**
