### PR TITLE
Implement delete page

### PR DESCRIPTION
**Pull request by alvinchow86**
Hook up the "Delete Page" button and get it working.

This is rebased off of https://github.com/scragg0x/realms-wiki/pull/81 because I need some changes from there, to get the actual difference see https://github.com/doordash/realms-wiki/compare/rename-page-fix...doordash:delete-page?expand=1

- `gittle.rm()` only touches the index, seems like we actually have to remove the file ourselves..
- added some simple JS that prompts the user, and adds a confirmation after successful delete
- apparently `gittle.rm()` (or rather `dulinger`) doesn't take unicode input, had to make sure its UTF8
- fixed the `test_delete_page` test, it wasn't actually really testing anything because no page was created. (before my fix it fails, but passes after)
- upgraded gittle to 0.5.0, why not

image
image

More than happy to make any tweaks or style fixes if needed

### CODE REVIEW

**Comment by scragg0x** [comment]
Very nice thanks!

**Comment by alvinchow86** [comment]
ah whoops, there was one more commit in the other branch https://github.com/scragg0x/realms-wiki/pull/81, https://github.com/doordash/realms-wiki/commit/b517e7e71441a5d9c1414e1774c060712920d5df, that we may want to get in

**Comment by scragg0x** [comment]
Oh thanks, I just saw that.  I should start at the bottom of the list.

**Comment by alvinchow86** [comment]
One more improvement idea - it might be less obtrusive to avoid the second "delete confirmation popup" and do a flashmessage instead or something

**Comment by scragg0x** [comment]
I agree

**Pull request merged**
