### PR TITLE
Switch from marked to markdown-it markdown renderer

### PR DESCRIPTION
**Pull request by gazpachoking**
Had a few issues with the marked renderer, and decided to see how easy it would be to switch it out. markdown-it looks a bit more actively updated, flexible, and has nice extensions so I switched that in. I think it would also be nice if the renderer options/extensions could be specified from the realms config file, but I haven't tried anything like that yet.

It'd be lovely if someone tested this out on their wiki, I'm not sure how compatible it is with the current renderer. Also, I don't javascript very often, so I'm not sure I did that bit right either. Any comments are welcome.

TODO:
- [x] Restore anchors for linking to headings within a page.

These issues may relate:
#106 
#117

### CODE REVIEW

**Comment by gazpachoking** [comment]
Running this on our prod site now (http://flexget.com), a couple small tweaks were needed to our markdown, but we are liking this engine better.

**Comment by gazpachoking** [comment]
So, I want to add back in the anchors to the headings, and this looks like a markdown-it extension that will do it https://www.npmjs.com/package/markdown-it-anchor  it doesn't look like that package is on bower though. @scragg0x (or anyone who knows about javascripty stuff) is there a clean way to include this if I can't just add it to the bower requirements?

**Comment by scragg0x** [comment]
@gazpachoking I usually use webpack/npm for new projects but realms is simple with no frontend build tools.  You could get this file, https://wzrd.in/standalone/markdown-it-anchor@latest and toss it into realms and try it out.

**Comment by scragg0x** [comment]
I got it from here btw: https://jsfiddle.net/9ukc8dy6/

**Comment by gazpachoking** [comment]
@scragg0x Thanks, that seems to work. I think that should be all of the old functionality restored now.

**Pull request merged**
