### PR TITLE
Improved installation steps + other small improvements.

### PR DESCRIPTION
**Pull request by magic890**
Added installation instructions for CentOS and Red Hat Enterprise Linux.
Other small improvements across the file.

### CODE REVIEW

**Comment by scragg0x** [comment]
Oops, there must be a conflict with your last PR I merged.

**Comment by magic890** [comment]
What I have to do to solve this conflicts?
I've repeated the same changes of the previous patch (my fault, I started another branch instead of continuing on patch-1), plus added more contents.

Are you able to take this patch-2 into the master? I don't know how to solve conflicts.

**Comment by scragg0x** [comment]
I think you would need to pull my master into your forked master and then merge your master into your patch-2 branch (at this point you will resolve a trivial conflict).  That merge commit should show up here.  I can merge this in by command line later if need be.

**Comment by magic890** [comment]
Now it's ready to be merged!

**Pull request merged**
