### PR TITLE
Updated Dockerfile

### LINKED ISSUE #36: Docker locks up in my_init
When running the current Docker build, the VM endlessly cycles in `/sbin/my_init`, with log messages like:
```
./run: line 33: setuid: command not found
./run: line 34: setgid: command not found
./run: line 39: respawn: command not found
```
It seemed something is amiss with the base image? I tried swapping out `realms-base` for:
```
FROM phusion/baseimage:0.9.15
RUN useradd -M deploy
```
But that had no effect.

### LINKED ISSUE #121: Docker: Please provide documentation with persistent Data
I tried to figure out how to store persistent data via [Docker volumes](https://docs.docker.com/engine/userguide/dockervolumes/) even by using "${REALMS_WIKI_CONFIG}", which is blocked by https://github.com/scragg0x/realms-wiki/pull/115, or providing an own ```realms-wiki.json``` via volume mount.
It would be very good to know, where and how to adjust the configuration, to be able to store data at a place where it could be placed on one (or more) volume(s).

Many thanks, Jan.

### PR DESCRIPTION
**Pull request by lanrat**
- does not start container as root
- uses volumes for persistent data (fixes #121)
- configurable at run-time via environment variables
- smaller image size (helps #102)
- can be connected to an automated build on the docker hub (no manual pushing binary images)
- logs to stdout and stderr to use docker logging as it should
- should fix #36

### CODE REVIEW

**Comment by lanrat** [comment]
@scragg0x do you mind updating realms/realms-wiki on the docker hub to use this as a new docker file for automated builds and adding ubuntu:trusty as repository link?

This would make the docker hub automatically update the docker image automatically every time there is an update on github.
https://hub.docker.com/r/realms/realms-wiki/~/settings/automated-builds/

Thanks!

**Comment by stevezau** [comment]
@lanrat thanks for updating this.. i don't think this has been updated on docker hub yet? Are you using it standalone?

**Comment by lanrat** [comment]
I'm using my own local build. It would be nice if @scragg0x could setup the automated build as mentioned in my previous comment.

**Comment by scragg0x** [comment]
I updated the docker image.  I don't yet have a fully automated build process yet.  Although I do have a script to publish to pypi and docker when I create a new version.

**Comment by lanrat** [comment]
@scragg0x if you follow the steps listed here (https://docs.docker.com/docker-hub/builds/) the Docker Hub will create an automated build from the git repository.

**Comment by stevezau** [comment]
@lanrat any reason why you used a virtualenv here? Seems unnecessary for a docker container?

Also, I assume wiki user was used for security reasons? Is that also really necessary? (I'm not that familiar with security best practice on docker)

**Comment by lanrat** [comment]
@stevezau virtualenv is not strictly required but it does not hurt either. I used to to try to keep the dockerfile inline with the install instructions in the README.

Without the wiki user the docker container would run as root which is a bad security practice.

**Comment by stevezau** [comment]
@lanrat another question, there is no support for setting a custom wiki json file? Should that be added or is there another way to do it?

**Comment by lanrat** [comment]
@stevezau any individual custom options can be specified as an environment variable: `docker run -e REALMS_VAR=VALUE`.
An entire custom config can be specified as a volume: `docker run -v /path/to/realms-wiki.json:/home/wiki/realms-wiki/realms-wiki.json`.

**Comment by stevezau** [comment]
@lanrat good point.. hmm perhaps an update to the README is in order.

**Pull request merged**
